# Generated by Django 4.1.3 on 2025-02-22 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('bio', models.CharField(max_length=400)),
                ('uid', models.CharField(max_length=50)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_artist', models.BooleanField(default=False)),
            ],
        ),
    ]
