# Generated by Django 4.1.3 on 2025-02-22 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merchexchangeapi', '0002_artist_category_listing'),
    ]

    operations = [
        migrations.CreateModel(
            name='WishlistListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchexchangeapi.listing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchexchangeapi.user')),
            ],
        ),
    ]
