# Generated by Django 4.1.3 on 2025-03-11 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchexchangeapi', '0002_user_profile_pic_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.URLField(),
        ),
    ]
