# Generated by Django 4.1.3 on 2025-03-12 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchexchangeapi', '0003_alter_user_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
