# Generated by Django 4.1.3 on 2025-03-14 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchexchangeapi', '0004_category_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('label',)},
        ),
    ]
