# Generated by Django 4.1.3 on 2025-03-14 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchexchangeapi', '0005_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
