# Generated by Django 4.1.3 on 2025-03-17 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchexchangeapi', '0006_alter_artist_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artist',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
    ]
